create table answer (id bigint not null auto_increment, content varchar(255), correct bit not null, question_id bigint not null, primary key (id)) engine=InnoDB;
create table evaluation_details (id bigint not null auto_increment, end_time datetime(6), graduated bit not null, quiz_duration bigint, quiz_id bigint, quiz_percent_correct float not null, start_time datetime(6), training_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table question (id bigint not null auto_increment, content varchar(255) not null, quiz_id bigint not null, primary key (id)) engine=InnoDB;
create table quiz (id bigint not null auto_increment, created_date datetime(6), description varchar(255), expected_percent_correct float, name varchar(255), training_id bigint, primary key (id)) engine=InnoDB;
create table roles (role_id bigint not null auto_increment, name varchar(255), primary key (role_id)) engine=InnoDB;
create table training (id bigint not null auto_increment, description varchar(255), path_to_training varchar(255), training_title varchar(255), primary key (id)) engine=InnoDB;
create table users (user_id bigint not null auto_increment, enabled bit not null, first_name varchar(255), is_supervised_by bigint, last_name varchar(255), password varchar(255), username varchar(255), primary key (user_id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table answer add constraint FK8frr4bcabmmeyyu60qt7iiblo foreign key (question_id) references question (id);
alter table evaluation_details add constraint FKjfq171l56xghg88o7vj3glv42 foreign key (training_id) references training (id);
alter table evaluation_details add constraint FKn4c3umoqdp8sb2d2begur0l3k foreign key (user_id) references users (user_id);
alter table question add constraint FKb0yh0c1qaxfwlcnwo9dms2txf foreign key (quiz_id) references quiz (id);
alter table quiz add constraint FKt4cc14nh3ca8r5lx4nbl6i2h8 foreign key (training_id) references training (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (role_id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (user_id);
