spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elp_dev?allowPublicKeyRetrieval=true&useSSL=false
    username: elp_dev_user
    password: pass
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-plarform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql